#!/usr/bin/env bash
# Prints the Homebrew formula for one published release.
#
# The release workflow's `tap` job pipes this into Formula/tekops.rb in
# lucassaldanha/homebrew-tekops. The formula installs the release tarballs
# as-is rather than building from source: the macOS one is the signed and
# notarized binary, and a source build would be neither.
#
# Usage: scripts/render-formula.sh <version> <path to SHA256SUMS>
set -euo pipefail

if [ $# -ne 2 ]; then
  echo "usage: render-formula.sh <version> <SHA256SUMS>" >&2
  exit 1
fi
version="${1#v}"
sums="$2"

# The asset for each platform, by the <arch>-<os> names build-release.sh
# publishes. Every one must be present: a formula missing a platform would
# still install on the others and fail only for whoever is on that one.
sha_for() {
  local asset="tekops-v$version-$1.tar.gz"
  local sha
  sha="$(awk -v a="$asset" '$2 == a || $2 == "*" a { print $1 }' "$sums")"
  if ! [[ "$sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "render-formula.sh: $sums has no checksum for $asset" >&2
    exit 1
  fi
  echo "$sha"
}

# Resolved before anything is printed, so a failure leaves no partial formula
# on stdout for the caller to commit.
macos_arm="$(sha_for aarch64-macos)"
linux_x86="$(sha_for x86_64-linux)"
linux_arm="$(sha_for aarch64-linux)"

base="https://github.com/lucassaldanha/tekops/releases/download/v$version"

cat <<EOF
# Generated by scripts/render-formula.sh in lucassaldanha/tekops on every
# release. Edits here are overwritten by the next one.
class Tekops < Formula
  desc "Helper CLI for operating a Teku node"
  homepage "https://github.com/lucassaldanha/tekops"
  version "$version"
  license "Apache-2.0"

  on_macos do
    # No Intel macOS build is published.
    depends_on arch: :arm64

    url "$base/tekops-v$version-aarch64-macos.tar.gz"
    sha256 "$macos_arm"
  end

  on_linux do
    on_intel do
      url "$base/tekops-v$version-x86_64-linux.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "$base/tekops-v$version-aarch64-linux.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "tekops"
    doc.install "USAGE.md"
    pkgshare.install "config.example.toml"
    generate_completions_from_executable(bin/"tekops", "autocomplete", "--print")
  end

  def caveats
    <<~EOS
      Update tekops with \`brew upgrade tekops\`; \`tekops update\` refuses to
      replace a Homebrew-managed binary.

      An example config file is at:
        #{pkgshare}/config.example.toml
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tekops --version")
  end
end
EOF
